apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-greenpage
  namespace: dev
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: Greenpage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: my-podlevel-metadata
      labels:
        app: Greenpage
    spec:
      containers:
        - name: my-yellow-container
          image: longflew/ingress:GREENPAGE
          ports:
            - containerPort: 80